# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - "**/bin/**"
    - "**/db/schema.rb"
    - "**/db/migrate/**"
    - "**/vendor/**/*"
    - "**/node_modules/**/*"
  SuggestExtensions: false

require:
  - rubocop-rails

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false
